#pragma once

#include "ADKernelGrad.h"

/**
 * Thermal-migration (Soret / thermotransport) term of the split Cahn–Hilliard equation
 *
 *   dc/dt = div( M_c grad w ) - div( M_T grad T / T )
 *
 * This kernel supplies the weak form of the second divergence,
 *
 *   R_TM = - int_Omega ( M_T / T ) grad T . grad psi dV,
 *
 * so that the thermal flux is J_T = + M_T grad T / T.  The sign convention and the
 * units of M_T are entirely the responsibility of the `thermal_mobility` material
 * property: with Mohanty's M_Q = c(1-c)[beta_U Q_U* - beta_Zr Q_Zr*] > 0 the Zr
 * flux points up the temperature gradient (toward the hot end).
 *
 * No physical constants or unit system are hard-coded.  The full Jacobian with respect
 * to every variable that `thermal_mobility` or `T` depends on is generated by automatic
 * differentiation.
 */
class ADThermalMigration : public ADKernelGrad
{
public:
  static InputParameters validParams();

  ADThermalMigration(const InputParameters & parameters);

protected:
  virtual ADRealVectorValue precomputeQpResidual() override;

  /// Temperature value and gradient
  const ADVariableValue & _T;
  const ADVariableGradient & _grad_T;

  /// Thermal (thermotransport) mobility M_T
  const ADMaterialProperty<Real> & _MT;
};
